### ISSUE TITLE
[DAY ?][Attic] Eclipse never ends [NullRef]

### ISSUE THREAD

**Issue by AnayHoshino** [RobotHouseStudio/Rumu#22]
Summery: 
Eclipse does not end.
(Image Below)

![RumuEclipseNull](https://user-images.githubusercontent.com/58378494/73413323-68f40c80-435f-11ea-9de1-dab7d153ecb8.jpg)

**Comment by danoli3** [comment]
Yeah Window wasn't registering itself to day.

Fixed - 4 Review
